name: Matrix
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            os: ubuntu-latest
        exclude:
          - node-version: 12
            os: windows-latest

    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm ci

      - name: Test code
        continue-on-error: true
        id: test-code-id
        run: npm run test

      - name: Build Project
        run: npm run build
