name: Reusable Deploy
on:
  workflow_call: # It is call from execution-flow.
    inputs:
      my-variable:
        description: Variable from other workflow
        required: false
        default: dist
        type: string
    outputs:
      result:


jobs:
  deploy:
    outputs:
      result-output: ${{ steps.set-result-id.outputs.my-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.my-variable }}

      - name: List files
        run: ls

      - name: Deploy
        run: echo "Deploying..."

      - name: Output Information
        run: echo "Deploying..."

      - name: "Getting result"
        id: set-result-id
        run: echo "my-result=Everything_works_fine" >> $GITHUB_OUTPUT
